= Forsguiden API - ULTRABETA
:toc: left
:toc-title: Innehållsförteckning


WARNING: Pågående arbete, vad som helst kan ändras när som helst! :-)

== Bakgrund

Målet med Forsguiden API är att samla all information om sveriges forspaddlingsvatten och göra det tillgängligt i ett strukturerat, öppet och väldokumenterat format så att vem som helst ska kunna använda informationen för att bygga egna smarta webapplikationer och mobilappar.

== Informationsmodell

Forsguiden API definierar följande informationsonsobjekt:

* <<lan>> 
* <<vattendrag>>
* <<forsstracka>>

[[lan]]
=== Län

Representerar ett av sveriges 21 län.

==== JSON

[source,json]
{
    "id": 21,
    "namn": "Gävleborg"
}

[horizontal]
Id:: unik identiferare för länet (är alltid samma som länets länskod)
Namn:: länets namn

[[vattendrag]]
=== Vattendrag

Ett namngivet vattendrag som kan ligga i ett eller flera län.

==== JSON

[source,json]
{
    "id": 1,
    "namn": "Testeboån",
    "beskrivning": "Ån rinner genom ett flackt skogs- och myrlandskap mellan Ockelbo och Gävle. Testeboån var tidigare flottled och spår efter detta finns kvar på sina håll."
    "lan": [
        {
            "id": 21,
            "namn": "Gävleborg"
        }
    ],
}

[horizontal]
Id:: unik identifierare för vattendraget
Namn:: vattendragets namn
Beskrivning:: kort beskrivning av vattendraget
Län:: lista med <<lan>> som vattendraget rinner genom

[[forsstracka]]
=== Forssträcka

En sträcka man normalt paddlar som en tur från a till b.

==== JSON

[source,json]
{
    "id": 1,
    "namn": "Brännsågen-Åbyggeby",
    "gradering": { 
        "klass": "3+",
        "lyft": ["4", "4-","5"]
    }
    ,
    "langd": 6000,
    "fallhojd": 28,
    "koordinater": {
        "lat": 60.75627,
        "long": 17.03825
    },
    "flode": {
        "smhipunkt": 12020,
        "minimum": 20,
        "optimal": 30,
        "maximum": 100
    },
    "vattendrag": [
        {
            "id": 1,
            "namn": "Testeboån"
        }
    ],
    "lan": [
        {
            "id": 21,
            "namn": "Gävleborg"
        }
    ]
}

[horizontal]
Id:: unikt id för forssträckan
Namn:: det namn man normalt använder för att referera till forssträckan
Koordinater:: ungefärliga koordinater (long, lat) för forssträckan
Gradering:: anger den huvudsakliga graderingen av sträckan (med eventuella kortare lyft av svårare partier) 
Längd:: sträckans längd (meter)
Fallhöjd:: total höjdskillnad mellan sträckans start och slut (meter)
Flöde:: anger vid vilka flöden som turen är mest lämplig att paddla samt den punkt på SMHI's vattenwebb som kan användas för flödesprognos.
Vattendrag:: det eller de <<vattendrag>> som forssträckan följer (är normalt endast ett vattendrag)
Län:: det eller de <<lan>> som sträckan passerar (är normalt endast ett län)

== API

=== Dumpa allt

Hämtar all information om alla forsar och vattendrag i ett enda stort json-objekt.

.Anrop
[source,json]
GET /data.json

.Svar
[source,json]
{
    "lan": [ ... ],
    "vattendrag": [ ... ],
    "forsstrackor": [ ... ]
}

link:data.json[Dumpa allt]